spring.application.name=order-service
server.port=8083

spring.datasource.url=${ORDER_DB_URL}
spring.datasource.username=${ORDER_DB_USERNAME}
spring.datasource.password=${ORDER_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
